"""Make board private

Revision ID: 00fa0739d225
Revises: 57c856afcf64
Create Date: 2022-06-28 16:22:20.285637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00fa0739d225'
down_revision = '57c856afcf64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('privacy', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'privacy')
    # ### end Alembic commands ###
