"""add relation Board  table

Revision ID: 3126102fdade
Revises: 6416d8979792
Create Date: 2022-06-20 10:49:24.934807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3126102fdade'
down_revision = '6416d8979792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('save_pin_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('pin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], ),
    sa.ForeignKeyConstraint(['pin_id'], ['pin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('save_pin_board_id_fkey', 'save_pin', type_='foreignkey')
    op.drop_column('save_pin', 'board_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('save_pin', sa.Column('board_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('save_pin_board_id_fkey', 'save_pin', 'board', ['board_id'], ['id'])
    op.drop_table('save_pin_board')
    # ### end Alembic commands ###
