"""Make pin private

Revision ID: 654f857f9f12
Revises: 00fa0739d225
Create Date: 2022-06-28 18:42:01.531499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654f857f9f12'
down_revision = '00fa0739d225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pin', sa.Column('privacy', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pin', 'privacy')
    # ### end Alembic commands ###
