"""block user feature

Revision ID: 689effcda05e
Revises: df7ed609869e
Create Date: 2022-07-04 11:08:39.381572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689effcda05e'
down_revision = 'df7ed609869e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('block_user')
    # ### end Alembic commands ###
