"""tag relationship updated

Revision ID: df7ed609869e
Revises: 654f857f9f12
Create Date: 2022-06-29 15:29:11.647794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7ed609869e'
down_revision = '654f857f9f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pin_tags_tag_id_fkey', 'pin_tags', type_='foreignkey')
    op.create_foreign_key(None, 'pin_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_interest_user_id_fkey', 'user_interest', type_='foreignkey')
    op.drop_constraint('user_interest_tag_id_fkey', 'user_interest', type_='foreignkey')
    op.create_foreign_key(None, 'user_interest', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_interest', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_interest', type_='foreignkey')
    op.drop_constraint(None, 'user_interest', type_='foreignkey')
    op.create_foreign_key('user_interest_tag_id_fkey', 'user_interest', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key('user_interest_user_id_fkey', 'user_interest', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'pin_tags', type_='foreignkey')
    op.create_foreign_key('pin_tags_tag_id_fkey', 'pin_tags', 'tags', ['tag_id'], ['id'])
    # ### end Alembic commands ###
