"""create all tables again

Revision ID: fcae341782d8
Revises: 94244e450c16
Create Date: 2022-06-24 11:57:42.328979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcae341782d8'
down_revision = '94244e450c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pin_tags_pin_id_fkey', 'pin_tags', type_='foreignkey')
    op.create_foreign_key(None, 'pin_tags', 'pin', ['pin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pin_tags', type_='foreignkey')
    op.create_foreign_key('pin_tags_pin_id_fkey', 'pin_tags', 'pin', ['pin_id'], ['id'])
    # ### end Alembic commands ###
